In [1]:
import pandas as pd
import sqlite3
from sqlalchemy import create_engine

In [2]:
df = pd.read_csv("../data/cleaned_superstore.csv")

df.head()

,Order ID,Customer Name,Category,Sales,Quantity,Profit,Region,Order Date
0,O001,Rahul,Furniture,5000,2,800,South,2024-01-05
1,O002,Priya,Technology,12000,1,2500,East,2024-01-08
2,O003,Arjun,Office Supplies,800,4,120,West,2024-01-10
3,O004,Sneha,Furniture,3000,3,450,North,2024-01-12
4,O005,Ravi,Technology,9500,2,1800,South,2024-01-15

In [3]:
df.shape

(5, 8)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5 non-null      str
 1   Customer Name  5 non-null      str
 2   Category       5 non-null      str
 3   Sales          5 non-null      int64
 4   Quantity       5 non-null      int64
 5   Profit         5 non-null      int64
 6   Region         5 non-null      str
 7   Order Date     5 non-null      str
dtypes: int64(3), str(5)
memory usage: 452.0 bytes

In [5]:
conn = sqlite3.connect("../data/superstore.db")

In [6]:
df.to_sql("superstore", conn, if_exists="replace", index=False)

5

In [7]:
tables = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

tables

         name
0  superstore

In [8]:
query = """
SELECT *
FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

,Order ID,Customer Name,Category,Sales,Quantity,Profit,Region,Order Date
0,O001,Rahul,Furniture,5000,2,800,South,2024-01-05
1,O002,Priya,Technology,12000,1,2500,East,2024-01-08
2,O003,Arjun,Office Supplies,800,4,120,West,2024-01-10
3,O004,Sneha,Furniture,3000,3,450,North,2024-01-12
4,O005,Ravi,Technology,9500,2,1800,South,2024-01-15

In [10]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sales', 'Quantity', 'Profit', 'Region', 'Order Date']

In [11]:
columns = pd.read_sql("PRAGMA table_info(superstore);", conn)
columns

   cid           name     type  notnull dflt_value  pk
0    0       Order ID     TEXT        0       None   0
1    1  Customer Name     TEXT        0       None   0
2    2       Category     TEXT        0       None   0
3    3          Sales  INTEGER        0       None   0
4    4       Quantity  INTEGER        0       None   0
5    5         Profit  INTEGER        0       None   0
6    6         Region     TEXT        0       None   0
7    7     Order Date     TEXT        0       None   0

In [12]:
query = """
SELECT *
FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

,Order ID,Customer Name,Category,Sales,Quantity,Profit,Region,Order Date
0,O001,Rahul,Furniture,5000,2,800,South,2024-01-05
1,O002,Priya,Technology,12000,1,2500,East,2024-01-08
2,O003,Arjun,Office Supplies,800,4,120,West,2024-01-10
3,O004,Sneha,Furniture,3000,3,450,North,2024-01-12
4,O005,Ravi,Technology,9500,2,1800,South,2024-01-15

In [13]:
query = """
SELECT "Order ID",
       "Customer Name",
       Category,
       Sales,
       Profit
FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

  Order ID Customer Name         Category  Sales  Profit
0     O001         Rahul        Furniture   5000     800
1     O002         Priya       Technology  12000    2500
2     O003         Arjun  Office Supplies    800     120
3     O004         Sneha        Furniture   3000     450
4     O005          Ravi       Technology   9500    1800

In [14]:
query = """
SELECT "Order ID",
       "Customer Name",
       Sales,
       Profit
FROM superstore
WHERE Sales > 500
ORDER BY Sales DESC;
"""

pd.read_sql(query, conn)

  Order ID Customer Name  Sales  Profit
0     O002         Priya  12000    2500
1     O005          Ravi   9500    1800
2     O001         Rahul   5000     800
3     O004         Sneha   3000     450
4     O003         Arjun    800     120

In [15]:
query = """
SELECT "Order ID",
       "Customer Name",
       Sales
FROM superstore
ORDER BY Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  Order ID Customer Name  Sales
0     O002         Priya  12000
1     O005          Ravi   9500
2     O001         Rahul   5000
3     O004         Sneha   3000
4     O003         Arjun    800

In [16]:
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0       Technology        21500
1        Furniture         8000
2  Office Supplies          800

In [17]:
query = """
SELECT Category,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Category
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Profit
0       Technology          4300
1        Furniture          1250
2  Office Supplies           120

In [18]:
query = """
SELECT Region,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

  Region  Total_Sales
0  South        14500
1   East        12000
2  North         3000
3   West          800

In [19]:
query = """
SELECT Region,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Region
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

  Region  Total_Profit
0  South          2600
1   East          2500
2  North           450
3   West           120

In [20]:
query = """
SELECT "Customer Name",
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  Customer Name  Total_Sales
0         Priya        12000
1          Ravi         9500
2         Rahul         5000
3         Sneha         3000
4         Arjun          800

In [21]:
query = """
SELECT "Customer Name",
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Profit DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  Customer Name  Total_Profit
0         Priya          2500
1          Ravi          1800
2         Rahul           800
3         Sneha           450
4         Arjun           120

In [22]:
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
HAVING SUM(Sales) > 100000;
"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [Category, Total_Sales]
Index: []

In [23]:
query = """
SELECT
    "Customer Name",
    SUM(Sales) AS Total_Spending,

    CASE
        WHEN SUM(Sales) >= 5000 THEN 'High'
        WHEN SUM(Sales) >= 2000 THEN 'Medium'
        ELSE 'Low'
    END AS Customer_Segment

FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Spending DESC;
"""

pd.read_sql(query, conn)

  Customer Name  Total_Spending Customer_Segment
0         Priya           12000             High
1          Ravi            9500             High
2         Rahul            5000             High
3         Sneha            3000           Medium
4         Arjun             800              Low

In [24]:
query = """
SELECT
    strftime('%Y-%m', "Order Date") AS Month,
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Month
ORDER BY Month;
"""

pd.read_sql(query, conn)

     Month  Total_Sales
0  2024-01        30300

In [25]:
query = """
SELECT
    AVG(Sales) AS Average_Sales,
    MIN(Sales) AS Minimum_Sales,
    MAX(Sales) AS Maximum_Sales
FROM superstore;
"""

pd.read_sql(query, conn)

   Average_Sales  Minimum_Sales  Maximum_Sales
0         6060.0            800          12000

In [26]:
query = """
SELECT
    COUNT(*) AS Total_Orders,
    SUM(Sales) AS Total_Sales,
    SUM(Quantity) AS Total_Quantity,
    SUM(Profit) AS Total_Profit,
    AVG(Sales) AS Average_Sales
FROM superstore;
"""

pd.read_sql(query, conn)

   Total_Orders  Total_Sales  Total_Quantity  Total_Profit  Average_Sales
0             5        30300              12          5670         6060.0

In [27]:
query = """
SELECT
    "Customer Name",
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Customer Name"
HAVING SUM(Sales) > (
    SELECT AVG(Customer_Total)
    FROM (
        SELECT SUM(Sales) AS Customer_Total
        FROM superstore
        GROUP BY "Customer Name"
    )
)
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

  Customer Name  Total_Sales
0         Priya        12000
1          Ravi         9500

In [29]:
query = """
WITH region_sales AS (
    SELECT
        Region,
        SUM(Sales) AS Total_Sales
    FROM superstore
    GROUP BY Region
)

SELECT *
FROM region_sales
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

  Region  Total_Sales
0  South        14500
1   East        12000
2  North         3000
3   West          800

In [30]:
query = """
SELECT
    "Customer Name",
    SUM(Sales) AS Total_Sales,

    RANK() OVER (
        ORDER BY SUM(Sales) DESC
    ) AS Sales_Rank

FROM superstore
GROUP BY "Customer Name"
ORDER BY Sales_Rank;
"""

pd.read_sql(query, conn)

  Customer Name  Total_Sales  Sales_Rank
0         Priya        12000           1
1          Ravi         9500           2
2         Rahul         5000           3
3         Sneha         3000           4
4         Arjun          800           5

In [31]:
query = """
SELECT
    "Customer Name",
    SUM(Sales) AS Total_Sales,

    ROW_NUMBER() OVER (
        ORDER BY SUM(Sales) DESC
    ) AS Row_Number

FROM superstore
GROUP BY "Customer Name"
ORDER BY Row_Number;
"""

pd.read_sql(query, conn)

  Customer Name  Total_Sales  Row_Number
0         Priya        12000           1
1          Ravi         9500           2
2         Rahul         5000           3
3         Sneha         3000           4
4         Arjun          800           5

In [32]:
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS Month,
        SUM(Sales) AS Total_Sales
    FROM superstore
    GROUP BY Month
)

SELECT
    Month,
    Total_Sales,

    LAG(Total_Sales) OVER (
        ORDER BY Month
    ) AS Previous_Month_Sales

FROM monthly_sales
ORDER BY Month;
"""

pd.read_sql(query, conn)

     Month  Total_Sales Previous_Month_Sales
0  2024-01        30300                 None

In [33]:
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS Month,
        SUM(Sales) AS Total_Sales
    FROM superstore
    GROUP BY Month
)

SELECT
    Month,
    Total_Sales,

    LEAD(Total_Sales) OVER (
        ORDER BY Month
    ) AS Next_Month_Sales

FROM monthly_sales
ORDER BY Month;
"""

pd.read_sql(query, conn)

     Month  Total_Sales Next_Month_Sales
0  2024-01        30300             None

In [34]:
query = """
CREATE VIEW IF NOT EXISTS category_summary AS

SELECT
    Category,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    SUM(Quantity) AS Total_Quantity

FROM superstore

GROUP BY Category;
"""

conn.execute(query)
conn.commit()

In [35]:
query = """
SELECT *
FROM category_summary
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales  Total_Profit  Total_Quantity
0       Technology        21500          4300               3
1        Furniture         8000          1250               5
2  Office Supplies          800           120               4

In [36]:
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0       Technology        21500
1        Furniture         8000
2  Office Supplies          800

In [38]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [39]:
from scripts.database_utils import create_database, run_query

In [40]:
engine = create_database(
    "../data/cleaned_superstore.csv",
    "../data/superstore.db"
)

Database created successfully.

In [41]:
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

run_query(engine, query)

          Category  Total_Sales  Total_Profit
0       Technology        21500          4300
1        Furniture         8000          1250
2  Office Supplies          800           120